### PR TITLE
CI actually works (definitely!)

### PR DESCRIPTION
**Pull request by fjebaker**
Hi Tom! Congratulations on your talk at RSE Con! 🎉 I saw some pictures of it circulating, hope it went well! 

Inspired by that I decided to spend a bit of time revisiting those nasty CI problems we were encountering. I am happy to say, I think I finally found what was breaking the CI.

Commit messages have the details. The jist is: missing environment variables to make MPI run as root, and also trying to test with coverage seemed to make testing the backends go awry.

I've skipped both backend tests at the moment, because the output no longer matches the expected output (at least on my machine). The tests technically work, but because that string compare assert has a handful of differences, they fail.

Hoping this works for you too, so some of the CI bugs can finally be resolved.

### CODE REVIEW

**Comment by fjebaker** [comment]
(Oh I also took the liberty of merging your main branch changes, so that if these changes work and meet your approval, this can dovetail straight into main)

**Comment by fjebaker** [comment]
I chanced on this in an unrelated context today, but it's relevant regarding the subprocess coverage: https://coverage.readthedocs.io/en/latest/subprocess.html

**Comment by fjebaker** [comment]
I was trying this out and the `timeout` test is failing occasionally with the client sometimes attempting, sometimes not attempting, to reconnect to the server a few times. Sounds like a race condition somewhere

**Comment by fjebaker** [comment]
Apologies this ended up being a lot of commits, and I had to add a few new message types. It was all part of the debugging process, but I ensured that each commit is atomic so just rebase as needed if this is too messy.

Anyway, CI now consistently works in my docker container and act, and seems to work on the github runner too.

**Comment by fjebaker** [comment]
Mypy is too difficult

**Comment by TomMelt** [comment]
@fjebaker , thank you so much :pray: This is awesome. 

Can't wait to take a look :eyes: ... but it will probably take me a couple of days :grimacing: 

I can't believe we will finally have green boxes on the README :partying_face: :tada: :raised_hands:

**Comment by TomMelt** [comment]
> Mypy is too difficult

Agreed.

:disappointed: I'll go make another sacrifice at the mypy altar :goat:

**Comment by TomMelt** [comment]
> (Oh I also took the liberty of merging your main branch changes, so that if these changes work and meet your approval, this can dovetail straight into main)
> 
> Edit: sorry, this made viewing the diffs on github horrible, would recommend the ol'
> 
> ```
> git log 2f15a65d0d526d419da01cc4eed48456d07e38e0.. --stat --patch
> ```
> 
> instead

Thanks. That's super handy for me :+1:

**Pull request merged**
